push = require('lib.push')
Class = require('lib.class')
require('src.config')

require('src.classes.Starfield')
require('src.classes.ShelterMgr')
require('src.classes.Shelter')
require('src.classes.Base')
require('src.classes.Laser')
require('src.classes.Enemy')
require('src.classes.EnemyFormation')
require('src.classes.UFO')
require('src.states.BaseState')
require('src.states.StartState')
require('src.states.PlayState')
require('src.states.GameOverState')
require('src.StateMachine')