push = require('lib.push')
Class = require('lib.class')
require('src.config')

require('src.classes.Base')
require('src.classes.Laser')
require('src.states.BaseState')
require('src.states.StartState')
require('src.states.PlayState')
require('src.StateMachine')